frontend/models/Board.php
<?php

namespace app\models;

use Yii;
use common\models\User;

/**
 * This is the model class for table "board".
 *
 * @property integer $id
 * @property string $name
 * @property integer $admin_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property User $admin
 * @property BoardUser[] $boardUsers
 * @property Post[] $posts
 * @property Task[] $tasks
 */
class Board extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'board';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'admin_id'], 'required'],
            [['admin_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['admin_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['admin_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'admin_id' => 'Admin ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdmin()
    {
        return $this->hasOne(User::className(), ['id' => 'admin_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBoardUsers()
    {
        return $this->hasMany(BoardUser::className(), ['board_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosts()
    {
        return $this->hasMany(Post::className(), ['board_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(Task::className(), ['board_id' => 'id']);
    }

    // get list of boards in which the given user id is a member of
    public function getUserBoards($id) {
        return Board::find()
            ->join('INNER JOIN', 'board_user', 'board.id = board_user.board_id')
            ->where(['board_user.user_id' => $id])
            ->all();
    }
}

frontend/controllers/BoardController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\AccessControl;

use app\models\Board;
use app\models\BoardUser;

class BoardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'index'],
                'rules' => [
                    [
                        'actions' => ['create', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Displays a single Board model.
     * @param integer $id
     * @return mixed
     */
    public function actionIndex($id)
    {
        $board = $this->findModel($id);
        if (!Yii::$app->user->can('manageBoards', ['type' => 'board', 'item' => $board]) &&
            !Yii::$app->user->can('createCard', ['type' => 'board', 'item' => $board]))
            throw new CHttpException(403, 'You do not have permission to access this page.');

        // get list of users and their information for this board
        $userData = array();
        $users = BoardUser::getBoardUsers($board->id);
        for ($i = 0; $i < count($users); $i++) {
            //echo '<pre>'; print_r($user); echo '</pre>';
            $user = $users[$i];
            $userData[$user['id']] = $user + array(
                'isAdmin' => $user['id'] === $board->admin_id
            );
            $userData[$user['id']]['joined_at'] = date('M j Y', strtotime($userData[$user['id']]['joined_at']));
        }
        //echo '<pre>'; print_r($userData); echo '</pre>'; die;

        return $this->render('index', [
            'board' => $board,
            'userData' => $userData,
        ]);
    }

    /**
     * Creates a new Board model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Board();
        $post = Yii::$app->request->post();

        //if ($model->load(Yii::$app->request->post()) && $model->save()) {
        if (!empty($post['Board'])) {
            $post = $post['Board'];

            // sanitize
            $boardName = \yii\helpers\Html::encode($post['name']);

            $model->name = $boardName;
            if (empty($post['admin_id'])) {
                $model->admin_id = Yii::$app->user->id;
            } else {
                $admin_id = $post['admin_id'];
                if (preg_match('/^[0-9]+$/', $admin_id) === 0) {
                    throw new ForbiddenHttpException;
                }
                $model->admin_id = $admin_id;
            }
            $model->save();

            // create the user-board relationship model
            $board_user = new BoardUser();
            $board_user->board_id = $model->id;
            $board_user->user_id = Yii::$app->user->id;
            $board_user->save();

            // check if this is an admin user
            //if (strcasecmp(key(Yii::$app->authmanager->getRoles(Yii::$app->user->id)), 'admin') === 0) {
            return $this->redirect(['index', 'id' => $model->id]);
            //}
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionSavesocketid() {
        $id = Yii::$app->request->post('id');

        if (!filter_var($id, FILTER_SANITIZE_SPECIAL_CHARS)) {
            throw new ForbiddenHttpException;
        }
        Yii::$app->db->createCommand()->update('session', ['socketid' => $id], 'user_id = ' . Yii::$app->user->id)->execute();

        return json_encode(array(
            'status' => 'success'
        ));
    }

    /**
     * Finds the Board model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Board the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Board::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/board/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Board */

$this->title = 'Assembly - ' . Yii::t('app', 'Create New Board');
//$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Boards'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app', 'Create New Board');
?>
<div class="board-create">

    <h1><?= Html::encode(Yii::t('app', 'Create New Board')) ?></h1>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>

	<?php ActiveForm::end(); ?>

</div>

frontend/views/board/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use frontend\assets\AngularAsset;

AngularAsset::register($this);

$this->title = 'Assembly Board';
?>

<div class="board-app" ng-app="boardApp" ng-controller="BoardController">
	<?= $this->render('nav', ['board' => $board]); ?>

	<div class="row">
		<div class="col-md-12">
			<a class="btn btn-primary" id="createNewTask" data-toggle="modal" href="#createTaskModal">Create New Task</a>
		</div>

		<div class="col-md-8 board-tasks">
			<?php // use angular js to populate the list of tasks */ ?>
		</div>

		<div class="col-md-4 hidden-xs hidden-sm board-log">
			<?php // use angular js to populate the list of recent actions */ ?>
		</div>
	</div>

	<?= $this->render('modals', ['board' => $board]); ?>
</div>

<script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
<script type="text/javascript">
// initialize the socket which we'll use to communicate with the server
var socket = io('http://localhost:3000');
socket.on('connect', function () {
	setTimeout(function() {
	    $.ajax({
	    	'type': 'POST',
	    	'url': "<?= Url::to(['board/savesocketid']) ?>",
	    	'data': {
	    		'id': socket.id
	    	}
	    }).done(function(data) {
	    	socket.emit('joinBoards');
	    });
	}, 1000);
});

this_board_id = <?= $board->id ?>;
this_board_name  = "<?= Html::encode($board->name) ?>";
userData = <?= json_encode($userData) ?>;
<?php 
	$templateUrl = Yii::$app->getUrlManager()->getBaseUrl() . '/js/angularjs/templates/';
?>
angularTemplates = {
	'userManager': "<?= $templateUrl . 'user-manager.html' ?>",
	'editBoard': "<?= $templateUrl . 'edit-board.html' ?>",
};
</script>

frontend/views/board/modals.php
<div class="modal fade" id="editBoardModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edit Board</h4>
            </div>
            <div class="modal-body">
                <div class="input-group">
                    <label for="name">Board Name:</label>
                    <input type="text" class="form-control" name="name" value="{{boardName}}" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" ng-click="saveEditBoard()">Save</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="manageUsersModal" tabindex="-1" role="dialog" ng-controller="ManageUsersController">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Manage Users</h4>
            </div>
            <div class="modal-body">
                
            <user-manager></user-manager>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save Changes</button>-->
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="createTaskModal" tabindex="-1" role="dialog" ng-controller="CreateTaskController">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Create New Task</h4>
            </div>
            <div class="modal-body">
                
             <div class="form-group">
                <label for="description">Description:</label>
                <textarea class="form-control" rows="5" name="description"></textarea>
            </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" ng-click="saveCreateTask()">Save</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

frontend/views/board/nav.php
<?php
    use yii\helpers\Html;

    $user = Yii::$app->user;
?>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand ng-cloak" href="#">{{boardName}}</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left board-last-updated">
                <li><p class="navbar-text" style="text-indent: 15px;">Last Updated: <?= Html::encode(date('M j Y, G:iA', strtotime($board->updated_at))) ?></p></li>
            </ul>
            <?php if ($user->can('manageBoard', ['type' => 'board', 'item' => $board])): ?>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a data-toggle="modal" href="#editBoardModal">Edit Board</a></li>
                            <li><a data-toggle="modal" href="#manageUsersModal">Manage Users</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Delete Board</a></li>
                        </ul>
                    </li>
                </ul>
            <?php endif; ?>
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>